site_name: AntennaPod
site_url: https://requisitos-de-software.github.io/2021.2-AntennaPod

repo_name: AntennaPod
repo_url: https://github.com/Requisitos-de-Software/2021.2-AntennaPod

markdown_extensions:
  - attr_list
  - md_in_html


theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  palette:
    primary: light blue

nav:
  - Início: index.md
  - Planejamento: 
    - Metodologia: planejamento/metodologia.md
    - Heatmap: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
  - Pré-Rastreabilidade: 
    - Rich Picture: pre-rastreamento/richPicture.md
  - Elicitação:
    - Personas: elicitacao/personas.md
    - Técnicas:
      - Análise de Protocolo: elicitacao/analiseProtocolo.md
      - Brainstorm: elicitacao/brainstorm.md
      - Introspecção: elicitacao/introspeccao.md
      - Observação: elicitacao/observacao.md
    - Priorização: elicitacao/100reais.md
  - Modelagem:
    - Backlog: modelagem/backlog.md
    - Casos de uso: modelagem/casosDeUso.md
    - Cenários: modelagem/cenarios.md
    - Especificação Suplementar: modelagem/especificacaoSuplementar.md
    - Léxicos: modelagem/lexicos.md
    - NFR Framework: modelagem/nfr-framework
  - Análise:
    - Verificação:
      - Introdução:  analise/verificacao/verificacao-introducao.md
      - Backlog: analise/verificacao/verificacao-backlog
      - Casos de uso: analise/verificacao/casosDeUso.md
      - Cenários: analise/verificacao/cenarios.md
      - Especificação Suplementar: analise/verificacao/especificacao-suplementar.md
      - Léxico: analise/verificacao/verificacao-Lexicos.md
      - NFR Framework: analise/verificacao/verificacao-nfr-framework.md
    - Validação:
      - Comunicação Informal: analise/validacao/validacaoComunicacaoInformal.md
      - Prototipação: analise/validacao/validacaoPrototipacao.md
  - Pós-Rastreabilidade: 
    - Forward From: posRastreabilidade/forward-from.md
  - Atas de reuniões:
    - Fevereiro:
      - Dia 02: reunioes/02-02.md
      - Dia 09: reunioes/09-02.md
      - Dia 17: reunioes/17-02.md
      - Dia 23: reunioes/23-02.md
    - Março:
      - Dia 10: reunioes/10-03.md
      - Dia 24: reunioes/24-03.md
  - Apresentações:
    - Apresentação-1: apresentacoes/apresentacao1.md
    - Apresentação-2: apresentacoes/apresentacao2.md
    - Apresentação-3: apresentacoes/apresentacao3.md
    - Apresentação-4: apresentacoes/apresentacao4.md
    - Apresentação-5: apresentacoes/apresentacao5.md
  
extra_css:
  - 'css/style.css'
