site_name: AntennaPod
site_url: https://requisitos-de-software.github.io/2021.2-AntennaPod/

repo_name: AntennaPod
repo_url: https://github.com/Requisitos-de-Software/2021.2-AntennaPod

theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  palette:
    primary: light blue

nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastreamento: 
    - Rich Picture: richPicture.md
  - Elicitação:
    - Análise de Protocolo: analiseProtocolo.md
  - Apresentações:
    - Apresentação-1: apresentacoes/apresentacao1.md
  
extra_css:
  - 'css/style.css'