site_name: AntennaPod
site_url: https://requisitos-de-software.github.io/2021.2-AntennaPod

repo_name: AntennaPod
repo_url: https://github.com/Requisitos-de-Software/2021.2-AntennaPod

markdown_extensions:
  - attr_list
  - md_in_html


theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  palette:
    primary: light blue

nav:
  - Início: index.md
  - Planejamento: 
    - Metodologia: planejamento/metodologia.md
    - Heatmap: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
  - Pré-Rastreamento: 
    - Rich Picture: pre-rastreamento/richPicture.md
  - Elicitação:
    - Técnicas:
      - Análise de Protocolo: elicitacao/analiseProtocolo.md
      - Brainstorm: elicitacao/brainstorm.md
      - Introspecção: elicitacao/introspeccao.md
      - Observação: elicitacao/observacao.md
    - Priorização: elicitacao/100reais.md
  - Modelagem:
    - Casos de uso: 
      - Introdução: modelagem/casosDeUso/casosDeUso.md
      - Caso 01 - Baixar episódio: modelagem/casosDeUso/uc01.md
      - Caso 02 - Assinar podacast: modelagem/casosDeUso/uc02.md
      - Caso 03 - Visualizar lista de podcasts assinados: modelagem/casosDeUso/uc03.md
  - Atas de reuniões:
    - Fevereiro:
      - Dia 02: reunioes/02-02.md
      - Dia 09: reunioes/09-02.md
      - Dia 17: reunioes/17-02.md
      - Dia 23: reunioes/23-02.md
  - Apresentações:
    - Apresentação-1: apresentacoes/apresentacao1.md
    - Apresentação-2: apresentacoes/apresentacao2.md
  
extra_css:
  - 'css/style.css'